export const TRUECALLER_ANDROID_CUSTOMIZATIONS = {
  BUTTON_TEXTS: Object.freeze({
    CONTINUE: 'TRUECALLER_ANDROID_BUTTON_TEXT_CONTINUE',
    ACCEPT: 'TRUECALLER_ANDROID_BUTTON_TEXT_ACCEPT',
    CONFIRM: 'TRUECALLER_ANDROID_BUTTON_TEXT_CONFIRM',
    PROCEED: 'TRUECALLER_ANDROID_BUTTON_TEXT_PROCEED',
  }),
  BUTTON_STYLES: Object.freeze({
    ROUND: 'TRUECALLER_ANDROID_BUTTON_ROUND',
    RECTANGLE: 'TRUECALLER_ANDROID_BUTTON_RECTANGLE',
  }),
  FOOTER_BUTTON_TEXTS: Object.freeze({
    SKIP: 'TRUECALLER_ANDROID_FOOTER_BUTTON_TEXT_SKIP',
    ANOTHER_MOBILE_NUMBER:
      'TRUECALLER_ANDROID_FOOTER_BUTTON_TEXT_ANOTHER_MOBILE_NUMBER',
    ANOTHER_METHOD: 'TRUECALLER_ANDROID_FOOTER_BUTTON_TEXT_ANOTHER_METHOD',
    MANUALLY: 'TRUECALLER_ANDROID_FOOTER_BUTTON_TEXT_MANUALLY',
    LATER: 'TRUECALLER_ANDROID_FOOTER_BUTTON_TEXT_LATER',
  }),
  CONSENT_HEADING_TEXTS: Object.freeze({
    LOG_IN_TO: 'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_LOG_IN_TO',
    SIGN_UP_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_SIGN_UP_WITH',
    SIGN_IN_TO: 'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_SIGN_IN_TO',
    VERIFY_NUMBER_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_VERIFY_NUMBER_WITH',
    REGISTER_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_REGISTER_WITH',
    GET_STARTED_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_GET_STARTED_WITH',
    PROCEED_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_PROCEED_WITH',
    VERIFY_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_VERIFY_WITH',
    VERIFY_PROFILE_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_VERIFY_PROFILE_WITH',
    VERIFY_YOUR_PROFILE_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_VERIFY_YOUR_PROFILE_WITH',
    VERIFY_PHONE_NO_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_VERIFY_PHONE_NO_WITH',
    VERIFY_YOUR_NO_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_VERIFY_YOUR_NO_WITH',
    CONTINUE_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_CONTINUE_WITH',
    COMPLETE_ORDER_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_COMPLETE_ORDER_WITH',
    PLACE_ORDER_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_PLACE_ORDER_WITH',
    COMPLETE_BOOKING_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_COMPLETE_BOOKING_WITH',
    CHECKOUT_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_CHECKOUT_WITH',
    MANAGE_DETAILS_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_MANAGE_DETAILS_WITH',
    MANAGE_YOUR_DETAILS_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_MANAGE_YOUR_DETAILS_WITH',
    LOGIN_TO_WITH_ONE_TAP:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_LOGIN_TO_WITH_ONE_TAP',
    SUBSCRIBE_TO: 'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_SUBSCRIBE_TO',
    GET_UPDATES_FROM:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_GET_UPDATES_FROM',
    CONTINUE_READING_ON:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_CONTINUE_READING_ON',
    GET_NEW_UPDATES_FROM:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_GET_NEW_UPDATES_FROM',
    LOGIN_SIGNUP_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_TEXT_LOGIN_SIGNUP_WITH',
  }),
};

export const TRUECALLER_ANDROID_EVENTS = {
  TRUECALLER_SUCCESS: 'TruecallerAndroidSuccess',
  TRUECALLER_FAILURE: 'TruecallerAndroidFailure',
};

export const DEFAULT_BUTTON_TEXT_COLOR = '#FFFFFF';
export const DEFAULT_BUTTON_COLOR = '#212121';
